export const FETCH_FILES_REQUEST = 'FETCH_FILES_REQUEST';
export const FETCH_FILES_SUCCESS = 'FETCH_FILES_SUCCESS';
export const FETCH_FILES_FAILURE = 'FETCH_FILES_FAILURE';

export const FETCH_FILES_LIST_SUCCESS = 'FETCH_FILES_LIST_SUCCESS';

export const SET_FILTER = 'SET_FILTER';
